[package]
name = "kafka_delta_consumer"
version = "0.1.0"
edition = "2021"

[dependencies]
deltalake = { version = "0.18.0", features = ["datafusion"] }
tokio = { version = "1.38.0", features = ["macros"] }
chrono = "0.4.38"
rand = "0.8.5"
